/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kari (https://sketchfab.com/keetos349)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/katarina-league-of-legends-1b21953e3d0b44dc9aa9e226d86fe2ab
Title: Katarina - League Of Legends
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Katarina(props) {
  const { nodes, materials } = useGLTF("/katarina_-_league_of_legends.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.DefaultMaterial}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/katarina_-_league_of_legends.glb");
